spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booknest
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  cache:
    type: redis
    redis:
      time-to-live: 120000
      cache-null-values: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000
      refresh-token:
        expiration: 604800000

logging:
  level:
    com.booknest: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG